baseurl: /
title: Renee's Portfolio
languageCode: en-us
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
Author:
  avatar: img/avatar.png
  bio: I am a fourth year student completing a combined Houours in Cognitive Science of Language and Communications Studies
  name: Renee Boney
Params:
  authorbox: yes
  description: John Doe's Personal blog about everything
  logo:
    subtitle: Just another site
  mainSections:
    - post
    - docs
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no

markup:
  goldmark:
    renderer:
      unsafe: true
